[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.55.0"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture --baseURL $DEPLOY_PRIME_URL"
