[build]
publish = "public"
command = "hugo; sleep 50; false"

[context.production.environment]
HUGO_VERSION = "0.55.0"
GO_VERSION = "1.12.2"
RUBY_VERSION = "2.6.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.0"
