---
new_page_extension: md
auto_deploy: false
admin_path: "/static/insidenow"
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: content/testimonials
  label: Testimonials
  create: documents
  match: "**/*"
  templates:
  - testimonial
- type: directory
  path: content/press
  label: Press
  create: documents
  match: "**/*"
  templates:
  - press-article
- type: directory
  path: content/awards
  label: Awards
  create: documents
  match: "**/*"
  templates:
  - award
- type: directory
  path: content/old_awards
  label: Old Awards
  create: documents
  match: "**/*"
  templates:
  - old-award
- type: directory
  path: content/personnel
  label: Team
  create: documents
  match: "**/*"
  templates:
  - team-member
- type: directory
  path: content/remodels
  label: Remodels
  create: documents
  match: "**/*"
  templates:
  - remodel
- type: directory
  path: content/portfolio
  label: Home Portfolio
  create: documents
  match: "**/*"
  templates:
  - home-single-portfolio
- type: directory
  path: themes/site-theme/data/collections
  label: Collections
  create: documents
  match: "**/*"
upload_dir: OnPoint Custom Homes
public_path: https://res.cloudinary.com/onpointcustomhomes/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
